// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( fraudRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* fraudRequest ) UnmarshalJSON([]byte) error { return nil }
func ( fraudRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* fraudRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_fraudRequest *fraudRequest

func ( fraudResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* fraudResponse ) UnmarshalJSON([]byte) error { return nil }
func ( fraudResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* fraudResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_fraudResponse *fraudResponse
