// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package vector

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector(in *jlexer.Lexer, out *Transaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = float32(in.Float32())
			}
		case "installments":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Installments = float32(in.Float32())
			}
		case "requested_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RequestedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector(out *jwriter.Writer, in Transaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.Float32(float32(in.Amount))
	}
	{
		const prefix string = ",\"installments\":"
		out.RawString(prefix)
		out.Float32(float32(in.Installments))
	}
	{
		const prefix string = ",\"requested_at\":"
		out.RawString(prefix)
		out.String(string(in.RequestedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Transaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Transaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Transaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Transaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector(l, v)
}
func easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector1(in *jlexer.Lexer, out *Terminal) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "is_online":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsOnline = bool(in.Bool())
			}
		case "card_present":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CardPresent = bool(in.Bool())
			}
		case "km_from_home":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KmFromHome = float32(in.Float32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector1(out *jwriter.Writer, in Terminal) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"is_online\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsOnline))
	}
	{
		const prefix string = ",\"card_present\":"
		out.RawString(prefix)
		out.Bool(bool(in.CardPresent))
	}
	{
		const prefix string = ",\"km_from_home\":"
		out.RawString(prefix)
		out.Float32(float32(in.KmFromHome))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Terminal) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Terminal) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Terminal) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Terminal) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector1(l, v)
}
func easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector2(in *jlexer.Lexer, out *Payload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "transaction":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Transaction).UnmarshalEasyJSON(in)
			}
		case "customer":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Customer).UnmarshalEasyJSON(in)
			}
		case "merchant":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Merchant).UnmarshalEasyJSON(in)
			}
		case "terminal":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Terminal).UnmarshalEasyJSON(in)
			}
		case "last_transaction":
			if in.IsNull() {
				in.Skip()
				out.LastTransaction = nil
			} else {
				if out.LastTransaction == nil {
					out.LastTransaction = new(LastTransaction)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.LastTransaction).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector2(out *jwriter.Writer, in Payload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"transaction\":"
		out.RawString(prefix[1:])
		(in.Transaction).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"customer\":"
		out.RawString(prefix)
		(in.Customer).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"merchant\":"
		out.RawString(prefix)
		(in.Merchant).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"terminal\":"
		out.RawString(prefix)
		(in.Terminal).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"last_transaction\":"
		out.RawString(prefix)
		if in.LastTransaction == nil {
			out.RawString("null")
		} else {
			(*in.LastTransaction).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Payload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Payload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Payload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Payload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector2(l, v)
}
func easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector3(in *jlexer.Lexer, out *NormalizationConstants) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "max_amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxAmount = float32(in.Float32())
			}
		case "max_installments":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxInstallments = float32(in.Float32())
			}
		case "amount_vs_avg_ratio":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AmountVsAvgRatio = float32(in.Float32())
			}
		case "max_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxMinutes = float32(in.Float32())
			}
		case "max_km":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxKm = float32(in.Float32())
			}
		case "max_tx_count_24h":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxTxCount24h = float32(in.Float32())
			}
		case "max_merchant_avg_amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxMerchantAvgAmount = float32(in.Float32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector3(out *jwriter.Writer, in NormalizationConstants) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"max_amount\":"
		out.RawString(prefix[1:])
		out.Float32(float32(in.MaxAmount))
	}
	{
		const prefix string = ",\"max_installments\":"
		out.RawString(prefix)
		out.Float32(float32(in.MaxInstallments))
	}
	{
		const prefix string = ",\"amount_vs_avg_ratio\":"
		out.RawString(prefix)
		out.Float32(float32(in.AmountVsAvgRatio))
	}
	{
		const prefix string = ",\"max_minutes\":"
		out.RawString(prefix)
		out.Float32(float32(in.MaxMinutes))
	}
	{
		const prefix string = ",\"max_km\":"
		out.RawString(prefix)
		out.Float32(float32(in.MaxKm))
	}
	{
		const prefix string = ",\"max_tx_count_24h\":"
		out.RawString(prefix)
		out.Float32(float32(in.MaxTxCount24h))
	}
	{
		const prefix string = ",\"max_merchant_avg_amount\":"
		out.RawString(prefix)
		out.Float32(float32(in.MaxMerchantAvgAmount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NormalizationConstants) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NormalizationConstants) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NormalizationConstants) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NormalizationConstants) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector3(l, v)
}
func easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector4(in *jlexer.Lexer, out *Merchant) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "mcc":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MCC = string(in.String())
			}
		case "avg_amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvgAmount = float32(in.Float32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector4(out *jwriter.Writer, in Merchant) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"mcc\":"
		out.RawString(prefix)
		out.String(string(in.MCC))
	}
	{
		const prefix string = ",\"avg_amount\":"
		out.RawString(prefix)
		out.Float32(float32(in.AvgAmount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Merchant) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Merchant) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Merchant) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Merchant) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector4(l, v)
}
func easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector5(in *jlexer.Lexer, out *LastTransaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = string(in.String())
			}
		case "km_from_current":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KmFromCurrent = float32(in.Float32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector5(out *jwriter.Writer, in LastTransaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix[1:])
		out.String(string(in.Timestamp))
	}
	{
		const prefix string = ",\"km_from_current\":"
		out.RawString(prefix)
		out.Float32(float32(in.KmFromCurrent))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LastTransaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LastTransaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LastTransaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LastTransaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector5(l, v)
}
func easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector6(in *jlexer.Lexer, out *Customer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "avg_amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvgAmount = float32(in.Float32())
			}
		case "tx_count_24h":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxCount24h = float32(in.Float32())
			}
		case "known_merchants":
			if in.IsNull() {
				in.Skip()
				out.KnownMerchants = nil
			} else {
				in.Delim('[')
				if out.KnownMerchants == nil {
					if !in.IsDelim(']') {
						out.KnownMerchants = make([]string, 0, 4)
					} else {
						out.KnownMerchants = []string{}
					}
				} else {
					out.KnownMerchants = (out.KnownMerchants)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.KnownMerchants = append(out.KnownMerchants, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector6(out *jwriter.Writer, in Customer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avg_amount\":"
		out.RawString(prefix[1:])
		out.Float32(float32(in.AvgAmount))
	}
	{
		const prefix string = ",\"tx_count_24h\":"
		out.RawString(prefix)
		out.Float32(float32(in.TxCount24h))
	}
	{
		const prefix string = ",\"known_merchants\":"
		out.RawString(prefix)
		if in.KnownMerchants == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.KnownMerchants {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Customer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Customer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44e5211fEncodeGithubComCarvalhodanielgTremDeFraudeInternalVector6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Customer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Customer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44e5211fDecodeGithubComCarvalhodanielgTremDeFraudeInternalVector6(l, v)
}
